### ISSUE TITLE
ServiceClient's gracefulDisconnect only takes current writes into consideration

### ISSUE THREAD

**Issue by nsauro** [tumblr/colossus#102]
Right now i can start a read from a remote source, and then use gracefulDisconnect to schedule a disconnect for when the read is complete.  Graceful disconnect currently only allows for the current writing operation to finish, and immediately disconnects any read.

This can probably be (easier) to implement with Dan's idea of using a state machine inside of the Controller.

**Comment by DanSimon** [comment]
So I think this is a bug in the controller layer rather than the service layer.  Both layers have logic for graceful disconnect and I think everything in `ServiceClient` is correct.  Basically when the Client's sent-buffer is empty it can call disconnect, which transfers control of the graceful disconnect procedure to the controller layer.

However, in the controller layer, graceful disconnect will wait for an output stream to complete, but not for an input stream.  That's the problem.
