### ISSUE TITLE
graceful shutdown of ServiceServers

### ISSUE THREAD

**Issue by nsauro** [tumblr/colossus#18]
Implementing a shutdown scheme in which current connections are not all suddenly killed.  Details need to be fleshed a bit, but just to get the ball rolling..implementing  a state with the following characteristics:

- accept no new connections
- allow drainage of all existing shorter lived connections
- for any longer lived connections,  sending a proper disconnect

Details to follow as we get closer to implementing this.

**Comment by DanSimon** [comment]
This should be split up into two separate issues.  There's graceful shutdown of a single connection and shutdown of a whole server.  They're separate since shutting down a connection can happen per connection and is a matter of allowing outstanding requests to complete without accepting new ones.  Shutting down a server involves all that plus watching total open connections and doing timeouts.

This issue will be for just the connection, since that's the part that's in the service layer.

**Comment by DanSimon** [comment]
Implemented in services, I'll create another issue for servers
