### ISSUE TITLE
Make codecs configurable through the DSL

### ISSUE THREAD

**Issue by DanSimon** [tumblr/colossus#3]
Right now when starting a service server or client, there's no way to configure the codec that's created.  This is largely because the codec is created by the implicitly provided `CodecProvider`.  This hasn't really been an issue since most codecs have no configuration right now, but that definitely will be changing soon.

**Comment by zgagnon** [comment]
Use case I've currently been encountering: I have a service which requests images of up to 10Mb in size, plus headers. Parser limit is currently set to the default, 1Mb. Whenever I get an image over this size, it causes the parser to throw an exception. I'd like a way to configure the Http codec so that I can handle these 10Mb images.

**Comment by DanSimon** [comment]
This is basically doable now by overriding or creating new CodecProviders
