### ISSUE TITLE
Design a better Http Routing DSL

### ISSUE THREAD

**Issue by DanSimon** [tumblr/colossus#392]
The current routing DSL leaves a lot to be desired.  While nice for examples and basic stuff, it's very slow and pretty limited in features.

I've tried to build better DSL's using extractors, but I'm convinced the way forward is to stop using extractors and fully create a routing DSL from the ground up.  We've also had discussions in the past about improving this, but only in a vague sense.  So I'd like this issue to settle on an actual API.

I'm envisioning something along the lines of:

``` scala
val routes = Routes (
  Route(Get / "foo" / "bar" / String / Integer) to doTheThing,
  Route(Post / "something" / *) withParameter[Int]("num") to doTheOtherThing
)

def doTheThing(request: HttpRequest, a: String, b: Int): Callback[HttpResponse] = {}
def doTheOtherThing(request: HttpRequest, num: Int): Callback[HttpResponse] =  {}

Server.start(//...
  //...
  def handle = routes.asHandler

```

So the idea would be you'd build your routes once and have the whole thing converted into some kind of optimized function that would become the actual request handler.

I don't want it to get too crazy, but I think the following is a reasonable wishlist
- match requests based on method, path, headers, query string parameters
- forward routes to functions
- extract path segments, headers, parameters into function arguments
- wildcard matching in paths, including variable-length wildcards
- maybe add body parsing and extraction

In addition, it should meet the following goals:
- All type-checking done at compile-time
- At least 90% as performant as directly writing regular if-statements on `HttpRequest`.  Basic routes that just do simple matching on things like method and path should be ideally 99% as fast.

**Comment by nsauro** [comment]
So, my initial thoughts are:

- The functions that the `Router` routes to need to belong to classes/objects(lets just call them "Controllers" for now) that are created prior to the Router creation.  This is so that things that need access to `WorkerRef`s can be created(ie: `ServiceClient`s).  A Controller would hold a reference to various `ServiceClient`s and other components.
- Depending on how applications are built, Controllers would also need to respond to delegator messages, so that they can react to external events(ie:config changes). 

I think introducing a trait `Router` which can build this routing data structure, affords the most flexibility.  The user could then just provide an implementation of this(or extend some base class for simple cases).  The idea here is to separate out routing logic into its own place, so that more complex services with lots of routes have a single place where it is obvious which routes are going to which controllers.
It would work something like:
- Server is started
- Clients/etc are all created
- Controllers are all created, and the Clients that they require are passed in
- A Router is created, and all the Controllers get passed in
- The Router provides a map of Route to Controller function
- A RouteMap is generated, and this can then be used by the Service in its `handle` function.

Def need to think through more of this.

**Comment by deterdw** [comment]
If you don't know it already, you might want to take a look at https://github.com/teamon/play-navigator, as it implements a similar kind of routing DSL to what you seem to be envisioning here.

I also think that with a complex app (say 100+ routes), you need something with better performance than a linear search through if-else branches. I have an unpublished little POC that uses a dynamic prefix tree (like a trie but also including parsers for argument extraction) which should be way better for complex routing. You're welcome to contact me about this when you come to implementation time on this issue.

Anyway, +1 for the issue -- I would certainly like to see a useable HTTP router in Colossus along the lines envisaged here.

**Comment by DanSimon** [comment]
Yeah actually some of the ideas I laid out are very much inspired by navigator.  An old version of Colossus (pre-open-source) actually had a sort-of fork of navigator included, but that was when the architecture was quite different and it did a bunch of crazy stuff with reflection, so I'm hoping to avoid most of that this time around but still get similar functionality.

Also in total agreement about prefix trees, which I should have put as a requirement since it is definitely part of the plan.  Tries with parsers sound pretty cool, if you have any example code on github I'd be interested in taking a look.

**Comment by benblack86** [comment]
Closing for now as this should be recreated as an RFC.
