### ISSUE TITLE
Load balancing error reporting

### ISSUE THREAD

**Issue by benblack86** [tumblr/colossus#428]
With the load balancer configured with retries, if an error occurs it will retry with a different host without reporting the error. It would be cool if we could get this info (problem host, exception) into a metric.

**Comment by DanSimon** [comment]
The error doesn't get reported but actually it does tick the metrics.  Metrics are handled by the individual clients which don't behave differently when part of a load balancer, but the reason it's not logged is because the failed callback is recovered and forwarded to another client in the pool.  

It should be pretty easy to log errors even when retries are successful, but we should make it configurable since I think in some cases if one remote host in the pool goes down, we don't want to start spamming error logs if the requests are successfully retried on other nodes.

**Comment by benblack86** [comment]
Going to close as an old ticket, but will think about with the service clients changes I'm looking at.
