### ISSUE TITLE
Is it possible to mix HttpService and StreamingHttpService together?

### ISSUE THREAD

**Issue by hntd187** [tumblr/colossus#446]
Hi,

I have some Services I'd like to mix in some streaming responses and some standard json responses, but it doesn't seem obvious how I would implement them both other than to have 2 separate services running on 2 separate ports. Is there a way to make use of both of these in one service?

**Comment by DanSimon** [comment]
Unfortunately the streaming and non-streaming interfaces cannot be mixed in a single service, however if you have some routes where you effectively just want to return a simple result without any streaming, you can use `StreamingHttpResponse.fromStatic(response)` which takes a regular `HttpResponse` and converts it into a stream.

I should also point out that the streaming API is pretty experimental and is actually undergoing a big redesign for the next major release.  The current plan is to make some fairly significant breaking changes to the API, including having a more actor-like interface and dropping `StreamingHttpRequest` and `StreamingHttpResponse`.   But I'd be interested to hear more about your use-case, since we only have one real project internally that uses it and could definitely use some more insight into what kinds of features people want when building a streaming service.

**Comment by benblack86** [comment]
I take it `StreamingHttpResponse.fromStatic(response)` was removed from 0.9? Looks like you have to do https://github.com/tumblr/colossus/blob/master/colossus-examples/src/main/scala/colossus-examples/StreamServiceExample.scala#L27 if you want to return a static response (need to explicitly set content-length yourself, otherwise it hangs).

**Comment by benblack86** [comment]
Closing this issue as there is another ticket re: streaming documentation.
