### ISSUE TITLE
Request Timeout per request

### ISSUE THREAD

**Issue by graineri** [tumblr/colossus#454]
I've been wandering around the code a little bit and noticed there is no way of specifying a request-timeout configuration per request in the `HttpClient`. It is actually a _global_ configuration that is set at the HTTP client configuration level.

Do you find this feasible?

**Comment by DanSimon** [comment]
Just to be clear, the configuration is global _per connection_, so depending on what you're doing, you can have different timeouts per request simply by creating a new client for each request.  I think right now that kind of workflow is a little cumbersome (since you have to manually remember to close each connection after sending the request), and it doesn't work in high-throughput situations, but it's doable.

When talking about requests being sent on the same connection having different timeouts, it's definitely something we can do but we simply haven't needed that kind of control.  On the technical side it would require some changes to how we currently check for timeouts, since right now we only have to look at the head of the queue, but I don't think it's anything insurmountable.

**Comment by graineri** [comment]
Correct. We have a high-throughput scenario (with HTTP Pipelining) where we need to configure a different timeout per request. However, if the timeout expires we would like the connection to be left open (right now, it seems that it closes the connection and triggers the reconnection logic).

Does it make sense? Am I overlooking something?

**Comment by DanSimon** [comment]
Yeah that's generally how things work.  A timeout can occur at two different points.  If a request is waiting to be sent and it times out, the request is essentially cancelled and the connection is unaffected.  If a request times out after it has been sent, then the connection is killed.

Your use case also sounds reasonable and is probably something we should support, it's just not one that we've had ourselves.  We have some planned upcoming work on client request processing in general so I think addressing this would fit in with that. 

On that note I think it's also definitely worth re-examining that connection logic as well.  Killing the connection on a timed-out sent request makes sense sometimes but not all the time.  I'd also like to better reflect the fact (possibly through different types of exceptions) that a timed-out pending request has the guarantee that it was definitely not received by the remote host, but a timed-out sent request may have been received, which is important for non-idempotent requests.

**Comment by graineri** [comment]
That sounds great! Thanks for taking the time to reply and prioritize this in the upcoming changes.

**Comment by benblack86** [comment]
Closing for now as this should be recreated as an RFC.
