### ISSUE TITLE
could not find implicit value for parameter sys: akka.actor.ActorSystem

### ISSUE THREAD

**Issue by klion26** [tumblr/colossus#457]
I copy the code from http://tumblr.github.io/colossus/docs/quickstart/. And get an error "could not find implicit value for parameter sys: akka.actor.ActorSystem", then add `implicit val system = ActorSystem()` before the sentence `implicit val io = IOSystem()` it works.

The error info is following:
`[error] /Users/qiucongxian/klion26/code/scala/Colossus/src/main/scala/Hello.scala:25: could not find implicit value for parameter sys: akka.actor.ActorSystem
[error] 	  implicit val io = IOSystem()
[error] 	                            ^
[error] /Users/qiucongxian/klion26/code/scala/Colossus/src/main/scala/Hello.scala:27: could not find implicit value for parameter io: colossus.IOSystem
[error] 		Server.start("hello-world", 9000){ worker => new HelloInitializer(worker) }
[error] 		                                 ^
[error] two errors found
[error] (compile:compileIncremental) Compilation failed`

**Comment by DanSimon** [comment]
Hey thanks for pointing that out.  Adding in the line that creates the `ActorSystem` is the right thing to do, so this is actually a twofold issue:

1.  The docs are out of date, I'll get that fixed
2.  The code in the docs _should_ be valid, but it seems we accidentally removed a constructor in the latest version.  We need to do some general cleanup around constructors and initialization functions anyway, so that'll probably get fixed in the next major release.
