### ISSUE TITLE
Possible to flush metric counters?

### ISSUE THREAD

**Issue by dre-hh** [tumblr/colossus#484]
short question:

I`ve setup a simple example with a LoggerSender and a counter which I incremented 3 Times. Now on every collection interval the logger outputs the last counter state  (which is 3). 

I understand this is supposed to work with only some kind of time series storage, where you would always report a value over time.  

However, what about a scenartio where you would report the counted value and remove/reset the counter.  Is it something one would implement in a custom sender, or is this scenario not supported by metrics package?

**Comment by DanSimon** [comment]
If you want the value to be reset automatically after it is reported, you can use a `Rate` instead of a `Counter`, which does exactly that.  A rate will increment an internal counter each time `hit()` is called, and once per collection-interval the rate will be reset to 0 after the value is read.  

When there are multiple collection intervals (which is the default case with 1 second and 1 minute intervals), the rate will keep separate counters for each interval.  So for example if you constantly hit a rate once per second, the 1-second value will always show 1 while the 1-minute value will show 60.  Also the `pruneEmpty` constructor parameter can be used to stop the rate from reporting anything when the value is 0.

**Comment by dre-hh** [comment]
thx, awesome
