### ISSUE TITLE
Document http streaming

### ISSUE THREAD

**Issue by benblack86** [tumblr/colossus#553]
Cause I don't know how to use it

**Comment by DanSimon** [comment]
Hey @benblack86 if you haven't already started, I'll write up some stuff about what currently exists.  It is definitely kinda confusing since there are two separate API's (with one built on top of the other) and they are _very confusingly_ named `HttpStream` and `StreamingHttp`.  Will definitely be interested in hearing people's opinions in how we can make that all cleaner!

**Comment by benblack86** [comment]
I haven't started, so I'll hand this to you :)

**Comment by benblack86** [comment]
I just added you as a collaborator to colossus, which you need to accept before I can actually assign.

**Comment by benblack86** [comment]
@DanSimon have you made any progress on this? Would be good to get it into 0.10.

**Comment by DanSimon** [comment]
Yes I've got a first draft of it mostly done.  Will probably need more added but it's a good start.  PR incoming soon.
