### ISSUE TITLE
support for chunk style encoding for streaming out http responses

### ISSUE THREAD

**Issue by nsauro** [tumblr/colossus#69]
Currently, we do not support chunk encoding for streaming out responses.

**Comment by DanSimon** [comment]
So this one is going to need a little thought.  One issue I ran into is if you're just piping a response from a client connection to a server connection, because the client is auto de-chunking the data, we need to re-chunk it in the server connection.  But this is really inefficient, so it would be far better if we could just pipe the raw data through which already contains the chunk headers.

I think we need to be able to make the explicit decision whether we want the codec to handle chunking/de-chunking transparently or whether we want it to pass data through verbatim.
