### ISSUE TITLE
HTTP API updates

### ISSUE THREAD

**Issue by nsauro** [tumblr/colossus#71]
Let's start adding some basic bells and whistles:

- some kind of fluency around building http requests
- some kind of fold/foldwith functionality on StreamedHttpResponses
- ability to pull types other than Strings from headers
- maybe a few others will add comments and such as they get fleshed out

**Comment by reeve** [comment]
I would think some specific handling for common headers would be nice. A good example is cookie - they're commonly used and reading/writing them is a PITA that we should handle in the framework.

**Comment by DanSimon** [comment]
I think we definitely need more cleanup on the pattern matching stuff.  I have a super-old branch somewhere with a new method where you create your routes outside the PartialFunction.  I think that may work really well since we can make the API much more flexible (since we're not at the mercy of `unapply`) and it should work nicely with the new `TagDecorator` for adding route and response code tags.

**Comment by nsauro** [comment]
Request parameters as well.  Having a way to match and type those would be badA

**Comment by mfirry** [comment]
Hi, I'm also facing the issue of having to manually add headers that (on other frameworks) would be default. Just curious to know if it would make any sense, for example, to have default Content-Type to plain/text. My two cents here. Thanks!

**Comment by DanSimon** [comment]
Closing this because the http API has improved dramatically since this was created.  I'm sure there's still plenty of room for improvements, but we can open smaller, more focused issues for those changes.
