### ISSUE TITLE
Introduce Master/Dev branch

### ISSUE THREAD

**Issue by nsauro** [tumblr/colossus#91]
In light of some of the instabilities that we are still working through for .6, I would like to officially propose master/dev branch git flow.  Let's keep master sane/happy/working/etc, and do all our work in dev/branches off of dev.

This is just a ticket to chat about it.

**Comment by DanSimon** [comment]
The model I think we should follow for now is master contains the latest and greatest, but should always compile and pass all tests.  If there are known bugs in master that's ok, but we should avoid introducing code into master that is known to be massively broken or only partially complete.

I'd like to keep that system because since we're under such heavy development, most people are going to look at master and want to make changes to that branch, but if we have lots of stuff in a "dev" branch, we'll probably end up with tons of merge conflicts.  I also want to avoid having large branches open for long periods of time.  I think having only one active branch helps enforce the practice of opening small, single-purpose feature branches.

Also remember we have the 0.5.x branch that we can still commit small bug fixes to, and push out more 0.5 releases.  I think having just those two long-term branches introduces enough managerial overhead, I'd be cautious about adding another, but if we can figure out exactly what should go in what branch along with a solid way to manage them, I'd be open to the possibility.
