### ISSUE TITLE
add a MetricsSender for both Logging and TSDB

### ISSUE THREAD

**Issue by nsauro** [tumblr/colossus#94]
I like metrics, logs and tsdb.  Why cannot I not have all 3?!  The simple fix here is to just make a new sender which does both.   A slightly better way of doing it would be to have a tiny DSL for a decorator.

**Comment by nsauro** [comment]
Also, in LoggerSenderActor, I would get rid of the verbose flag, and have the verbosity handled by log levels, and print more details as the level increases

**Comment by DanSimon** [comment]
If I'm reading this right, this doesn't seem necessary to me, you can just attach multiple reporters to the metrics, one with the tsdb sender and the other with the logger sender.  Alternatively we could make the `sender` field of the reporter config take a list of senders instead of just one, to make it easier to have multiple senders with the same filters, reporting frequency, etc.

**Comment by nsauro** [comment]
What I ended up implementing was actually not what I described here.  Checkout the PR..it's a pretty small change, which just allowed for using log levels to control the verbosity.
